# Generated by Django 3.1.1 on 2020-09-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaudit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scancsv',
            name='scancsv',
        ),
    ]
