# Generated by Django 3.1.1 on 2020-09-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaudit', '0002_remove_scancsv_scancsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='scancsv',
            name='appname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scancsv',
            name='appversion',
            field=models.TextField(blank=True),
        ),
    ]
