# Generated by Django 3.1.1 on 2020-09-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaudit', '0003_auto_20200916_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scancsv',
            name='appname',
        ),
        migrations.RemoveField(
            model_name='scancsv',
            name='appversion',
        ),
        migrations.AlterField(
            model_name='scancsv',
            name='name',
            field=models.TextField(),
        ),
    ]
