# Generated by Django 3.1.1 on 2020-09-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaudit', '0004_auto_20200916_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scancsv',
            old_name='name',
            new_name='appname',
        ),
    ]
