# Generated by Django 3.1.3 on 2020-11-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaudit', '0006_auto_20200917_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareEntitlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('serialnumber', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
