# Generated by Django 3.1.3 on 2020-11-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaudit', '0007_hardwareentitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareentitlement',
            name='computername',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hardwareentitlement',
            name='hostname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hardwareentitlement',
            name='status',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
