# Generated by Django 3.1.3 on 2020-11-09 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iaudit', '0008_auto_20201109_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardwareentitlement',
            old_name='computername',
            new_name='computer_name',
        ),
        migrations.RenameField(
            model_name='hardwareentitlement',
            old_name='serialnumber',
            new_name='hardware_serial',
        ),
        migrations.RemoveField(
            model_name='hardwareentitlement',
            name='hostid',
        ),
        migrations.AddField(
            model_name='hardwareentitlement',
            name='uuid',
            field=models.TextField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hardwareentitlement',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='hardwareentitlement',
            name='status',
            field=models.CharField(max_length=5),
        ),
    ]
